#!/bin/bash

# Submit slurm scripts every minute
submit_and_wait() {
  sbatch "$1" "$2" "$3" "$4"   # Submit the Slurm script with parameters
  sleep 1m     # Sleep for 1 minute
}

submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_110 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_110 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_110 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_120 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_120 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_120 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_140 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_140 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_140 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_150 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_150 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_150 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_160 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_160 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_160 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_210 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_210 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_210 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_220 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_220 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_220 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_230 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_230 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_230 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_240 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm both_310 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_310 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_320 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_330 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm wb_410 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_430 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_520 rank_pcnl_sh_co_d1 1000
submit_and_wait call_rank_pc_nl_shallow_collapse_dp1.slurm ch_700 rank_pcnl_sh_co_d1 1000