#!/bin/bash

# Submit slurm scripts every minute
submit_and_wait() {
  sbatch "$1" "$2" "$3" "$4"   # Submit the Slurm script with parameters
  sleep 1m     # Sleep for 1 minute
}

submit_and_wait call_pc_nl_collapse_random_embed.slurm both_110 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_110 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_110 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm both_120 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_120 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_120 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm both_140 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_140 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_140 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm both_150 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_150 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_150 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm both_160 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_160 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_160 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm both_210 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_210 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_210 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm both_220 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_220 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_220 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm both_230 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_230 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_230 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_240 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm both_310 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_310 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_320 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_330 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm wb_410 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_430 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_520 pcnl_co_re 1000
submit_and_wait call_pc_nl_collapse_random_embed.slurm ch_700 pcnl_co_re 1000